apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopi-app
  namespace: kube-system
  labels:
    k8s-app: gopi-app
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gopi-app
  template:
    metadata:
      labels:
        k8s-app: gopi-app
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: gopi-app
        image: {{ registry }}/{{ appname }}:{{ versionNum }}
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 300m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
        ports:
        - containerPort: 8080
          name: gopi-app
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: gopi-app
  namespace: kube-system
  labels:
    k8s-app: gopi-app
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Gopi-Music"
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: ui
    nodePort: 31337
  selector:
    k8s-app: gopi-app
