version: '2'

services:

  app:
    build: .
    ports:
    - 8919:8080
    depends_on:
    - mongodb
    hostname: app

  mongodb:
    build: mongodb/
    ports:
    - 27017:27017
    hostname: mongodb
    container_name: mongodb
    volumes:
    - music_data:/data/db:rw
    - music_data:/data/configdb:rw


volumes:
  music_data:
    external: true
