version: '2'

services:

  app:
    build: .
    ports:
    - 8080
    networks:
    - net
    depends_on:
    - mongodb
    hostname: app

  mongodb:
    build: mongodb/
    ports:
    - 27017:27017
    networks:
    - net
    depends_on:
    - elk
    hostname: mongodb
    container_name: mongodb
    volumes:
    - music_data:/data/db
    - music_data:/data/configdb


volumes:
  music_data:
    external: true
  music_elk:
    external: true

networks:
  net:
    driver: bridge